-- Journal Schema for RYTM
-- Run this in Supabase SQL Editor

-- =====================================================
-- 1. Drop old tables if migrating (CAREFUL!)
-- =====================================================
-- Uncomment these if you want to start fresh:
DROP TABLE IF EXISTS journal_entries CASCADE;
DROP TABLE IF EXISTS journal_messages CASCADE;
DROP TABLE IF EXISTS journal_threads CASCADE;

-- =====================================================
-- 2. Create journal_threads table
-- =====================================================
CREATE TABLE IF NOT EXISTS journal_threads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT, -- Can be auto-generated by LLM later
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'archived')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_message_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 3. Create journal_messages table
-- =====================================================
CREATE TABLE IF NOT EXISTS journal_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  thread_id UUID REFERENCES journal_threads(id) ON DELETE CASCADE, -- NULL for Free mode
  mode TEXT NOT NULL CHECK (mode IN ('free', 'guided')),
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 4. Create indexes for performance
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_threads_user_updated 
  ON journal_threads(user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_threads_user_last_message 
  ON journal_threads(user_id, last_message_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_user_date 
  ON journal_messages(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_thread_date 
  ON journal_messages(thread_id, created_at);

CREATE INDEX IF NOT EXISTS idx_messages_mode 
  ON journal_messages(user_id, mode, created_at DESC);

-- =====================================================
-- 5. RLS Policies for journal_threads
-- =====================================================
ALTER TABLE journal_threads ENABLE ROW LEVEL SECURITY;

-- Users can view their own threads
CREATE POLICY "Users can view own threads"
  ON journal_threads FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Users can create threads
CREATE POLICY "Users can create threads"
  ON journal_threads FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own threads
CREATE POLICY "Users can update own threads"
  ON journal_threads FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Users can delete their own threads
CREATE POLICY "Users can delete own threads"
  ON journal_threads FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- =====================================================
-- 6. RLS Policies for journal_messages
-- =====================================================
ALTER TABLE journal_messages ENABLE ROW LEVEL SECURITY;

-- Users can view their own messages
CREATE POLICY "Users can view own messages"
  ON journal_messages FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Users can create messages
CREATE POLICY "Users can create messages"
  ON journal_messages FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own messages (for edits)
CREATE POLICY "Users can update own messages"
  ON journal_messages FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Users can delete their own messages
CREATE POLICY "Users can delete own messages"
  ON journal_messages FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- =====================================================
-- 7. Function to auto-update thread.updated_at
-- =====================================================
CREATE OR REPLACE FUNCTION update_thread_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE journal_threads
  SET 
    updated_at = NOW(),
    last_message_at = NEW.created_at
  WHERE id = NEW.thread_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger when new message is inserted
DROP TRIGGER IF EXISTS trigger_update_thread_timestamp ON journal_messages;
CREATE TRIGGER trigger_update_thread_timestamp
  AFTER INSERT ON journal_messages
  FOR EACH ROW
  WHEN (NEW.thread_id IS NOT NULL)
  EXECUTE FUNCTION update_thread_timestamp();

-- =====================================================
-- 8. Helper function to get or create active thread
-- =====================================================
CREATE OR REPLACE FUNCTION get_or_create_active_thread(p_user_id UUID)
RETURNS UUID AS $$
DECLARE
  v_thread_id UUID;
BEGIN
  -- Try to find an active thread from today
  SELECT id INTO v_thread_id
  FROM journal_threads
  WHERE user_id = p_user_id
    AND status = 'active'
    AND DATE(created_at) = CURRENT_DATE
  ORDER BY last_message_at DESC
  LIMIT 1;

  -- If no thread exists, create one
  IF v_thread_id IS NULL THEN
    INSERT INTO journal_threads (user_id, title)
    VALUES (p_user_id, 'Journal - ' || TO_CHAR(NOW(), 'YYYY-MM-DD HH24:MI'))
    RETURNING id INTO v_thread_id;
  END IF;

  RETURN v_thread_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
